export const RUN_COMPARE = 'RUN_COMPARE'
export const LOAD_EXAMPLE_TEXTS = 'LOAD_EXAMPLE_TEXTS'

export const COMPARE_RESET = 'COMPARE_RESET'
export const COMPARE_PANEL_OPEN = 'COMPARE_PANEL_OPEN'
export const COMPARE_REQUEST = 'COMPARE_REQUEST'
export const COMPARE_SUCCESS = 'COMPARE_SUCCESS'
export const COMPARE_ERROR = 'COMPARE_ERROR'
export const COMPARE_VALIDATION_ERROR = 'COMPARE_VALIDATION_ERROR'

export const EXAMPLES_LOAD_REQUEST = 'EXAMPLES_LOAD_REQUEST'
export const EXAMPLES_LOAD_SUCCESS = 'EXAMPLES_LOAD_SUCCESS'
export const EXAMPLES_LOAD_ERROR = 'EXAMPLES_LOAD_ERROR'
