export const RUN_COMPARE = 'RUN_COMPARE'
export const LOAD_EXAMPLE_TEXTS = 'LOAD_EXAMPLE_TEXTS'

export const COMPARE_RESET = 'COMPARE_RESET'
export const COMPARE_PANEL_OPEN = 'COMPARE_PANEL_OPEN'
export const COMPARE_REQUEST = 'COMPARE_REQUEST'
export const COMPARE_SUCCESS = 'COMPARE_SUCCESS'
export const COMPARE_ERROR = 'COMPARE_ERROR'
export const COMPARE_VALIDATION_ERROR = 'COMPARE_VALIDATION_ERROR'

export const EXAMPLES_LOAD_REQUEST = 'EXAMPLES_LOAD_REQUEST'
export const EXAMPLES_LOAD_SUCCESS = 'EXAMPLES_LOAD_SUCCESS'
export const EXAMPLES_LOAD_ERROR = 'EXAMPLES_LOAD_ERROR'

// --- RAG module (namespaced under "rag/") ---
export const FETCH_JOB_DESCRIPTIONS = 'FETCH_JOB_DESCRIPTIONS'
export const FETCH_RESUMES = 'FETCH_RESUMES'
export const INGEST_RESUME = 'INGEST_RESUME'
export const INGEST_JD = 'INGEST_JD'
export const FIND_BEST_CANDIDATES = 'FIND_BEST_CANDIDATES'

export const RAG_REQUEST = 'RAG_REQUEST'
export const RAG_ERROR = 'RAG_ERROR'
export const RAG_SET_JOB_DESCRIPTIONS = 'RAG_SET_JOB_DESCRIPTIONS'
export const RAG_SET_RESUMES = 'RAG_SET_RESUMES'
export const RAG_SET_CANDIDATES = 'RAG_SET_CANDIDATES'
export const RAG_RESET_RESULTS = 'RAG_RESET_RESULTS'
